Rem 本脚本用于更改运行环境后，即运行完cas_change_context后，重新编译jar包并安装至maven本地仓库
Rem 此脚本运行完毕后，才可以运行deploy.bat打安装包

cd /d E:\CodeWorld\IdeaJavaProjects\utils
echo 开始安装utils模块...
call mvn clean install
echo utils模块已安装完毕...
pause

cd /d E:\CodeWorld\IdeaJavaProjects\cas
echo 开始安装cas模块...
call mvn clean install
echo cas模块安装完毕...
echo 安装完毕...
pause
